# Generated by Django 4.2.24 on 2025-09-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxurywares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='descricao',
            field=models.CharField(choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão de Crédito')], max_length=50, unique=True),
        ),
    ]
