# Generated by Django 4.2.24 on 2025-09-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxurywares', '0002_alter_formapagamento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(choices=[('Gold', 'Gold - 600€'), ('Silver', 'Silver - 250€'), ('Econômico', 'Econômico - 50€')], default='ECONOMICO', max_length=20),
        ),
    ]
