# Generated by Django 4.2.24 on 2025-09-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxurywares', '0003_cliente_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
