# Generated by Django 4.2.24 on 2025-09-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxurywares', '0004_alter_reserva_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
